nodes:
  spamhaus_EDROP:
    output: true
    prototype: spamhaus.EDROP
  badips-1543370727680:
    inputs: []
    output: true
    prototype: zeustracker.badips
  dshield_blocklist:
    output: true
    prototype: dshield.block
  inboundfeedlc:
    inputs:
      - inboundaggregator
    output: false
    prototype: stdlib.feedLCGreen
  inboundfeedhc:
    inputs:
      - inboundaggregator
    output: false
    prototype: stdlib.feedHCGreen
  spamhaus_DROP:
    output: true
    prototype: spamhaus.DROP
  inboundfeedhcvalues:
    inputs:
      - inboundaggregator
    output: false
    prototype: stdlib.feedHCGreenWithValue
  aggregatorIPv4Outbound-1543370742868:
    inputs:
      - badips-1543370727680
    output: true
    prototype: stdlib.aggregatorIPv4Outbound
  outboundfeedhcvalues:
    inputs:
      - aggregatorIPv4Outbound-1543370742868
    output: false
    prototype: stdlib.feedHCGreenWithValue
  wlWhiteListIPv4:
    inputs: []
    output: true
    prototype: stdlib.listIPv4Generic
  inboundaggregator:
    inputs:
      - spamhaus_DROP
      - spamhaus_EDROP
      - dshield_blocklist
      - wlWhiteListIPv4
    output: true
    prototype: stdlib.aggregatorIPv4Inbound
  inboundfeedmc:
    inputs:
      - inboundaggregator
    output: false
    prototype: stdlib.feedMCGreen
